(lang dune 3.24)

(name obscurity)

(generate_opam_files true)

(source
 (github carsonmagnuson/roborean))

(authors "Carson Glines <carsonmagnuson@gmail.com>")

(maintainers "Carson Glines <carsonmagnuson@gmail.com>")

(license "AGPL-3.0-or-later")

(package
 (name obscurity)
 (synopsis "Word obscurity scoring and Merriam-Webster dictionary proxy")
 (description "An OCaml/Dream microservice for the Roborean word-collection app. Scores word obscurity from corpus frequency data and proxies dictionary definitions from Merriam-Webster's API.")
 (depends ocaml dune dream cohttp-lwt-unix yojson dotenv)
 (tags
  ("ocaml" "dream" "dictionary" "nlp" "microservice")))

; See the complete stanza docs at https://dune.readthedocs.io/en/stable/reference/dune-project/index.html
